before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y default-jdk javascriptcoregtk-3.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev
dist: trusty
language: c
script: cd planck-c && make bundle-and-build && ./planck -e '(map inc (range 3))'
